const palette = {
	transparent: 'transparent',
	black: '#000',
	white: '#fff',
	gray: {
		'100': '#f5f5f5',
		'200': '#eeeeee',
		'300': '#e0e0e0',
		'400': '#bdbdbd',
		'500': '#9e9e9e',
		'600': '#757575',
		'700': '#616161',
		'800': '#424242',
		'900': '#212121',
	},
	red: '#d14746'
};

module.exports = {
	prefix: '',
	important: '#wpbody',
	separator: ':',
	theme: {
		screens: {
			sm: '640px',
			md: '768px',
			lg: '1024px',
			xl: '1136px',
		},
		colors: {
			transparent: palette.transparent,
			black: palette.black,
			white: palette.white,
			primary: palette.red,
			'link-primary': palette.red,
			'font-primary': palette.gray[800],
			'font-secondary': palette.gray[900],
			'pre-border': palette.gray[200],
			'table-border': palette.gray[400],
			'separator': palette.gray[400],
			'primary-btn': palette.white,
			'primary-btn-bg': palette.red
		},
		spacing: {
			'0': '0',
			'wide-margins': 'calc(50% - 50vw)',
			'container-padding': '3.333%',
			'gutter': '2.5rem',
			'section-y': '10rem',
			'subsection-y': '2.5rem',
			'heading-b': '6.667rem',
			'heading-in-col-b': '3.333rem',
			'text-block-b': '2rem',
			'following-text-block-t': '1.333rem',
			'default-block-b': '3.333rem',
			'list-indent': '2.5rem',
			'pre-padding': '2rem',
			'table-padding': '.5rem',
			'primary-btn-padding-x': '2rem',
			'primary-btn-padding-y': '1rem',
			'hamburger-w': '2rem',
			'hamburger-h': '1.4rem',
			'hamburger-line-w': '.2rem',
			'menu-spacing': '1rem'
		},
		backgroundColor: theme => theme('colors'),
		backgroundPosition: {
			bottom: 'bottom',
			center: 'center',
			left: 'left',
			'left-bottom': 'left bottom',
			'left-top': 'left top',
			right: 'right',
			'right-bottom': 'right bottom',
			'right-top': 'right top',
			top: 'top',
		},
		backgroundSize: {
			auto: 'auto',
			cover: 'cover',
			contain: 'contain',
		},
		borderColor: theme => ({
			...theme('colors'),
			default: theme('colors.gray.300', 'currentColor'),
		}),
		borderRadius: {
			none: '0',
			sm: '0.125rem',
			default: '0.25rem',
			lg: '0.5rem',
			full: '9999px',
		},
		borderWidth: {
			default: '1px',
			'0': '0',
			'1': '1px'
		},
		boxShadow: {
			default: '0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px 0 rgba(0, 0, 0, 0.06)',
			md: '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)',
			lg: '0 10px 15px -3px rgba(0, 0, 0, 0.1), 0 4px 6px -2px rgba(0, 0, 0, 0.05)',
			xl: '0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)',
			'2xl': '0 25px 50px -12px rgba(0, 0, 0, 0.25)',
			inner: 'inset 0 2px 4px 0 rgba(0, 0, 0, 0.06)',
			outline: '0 0 0 3px rgba(66, 153, 225, 0.5)',
			none: 'none',
		},
		container: {
			center: false,
		},
		cursor: {
			auto: 'auto',
			default: 'default',
			pointer: 'pointer',
			wait: 'wait',
			text: 'text',
			move: 'move',
			'not-allowed': 'not-allowed',
		},
		fill: {
			current: 'currentColor',
			white: palette.white
		},
		flex: {
			'1': '1 1 0%',
			auto: '1 1 auto',
			initial: '0 1 auto',
			none: 'none',
		},
		flexGrow: {
			'0': '0',
			default: '1',
		},
		flexShrink: {
			'0': '0',
			default: '1',
		},
		fontFamily: {
			'primary': [
				'sans-serif',
			],
		},
		fontSize: {
			'base': '10px',
			'lg-base': '12px',
			'regular': '1.333rem',
			'small': '1.3rem',
			'large': '1.7rem',
			'large-1': '4.7rem',
			'large-2': '2.667rem',
			'large-3': '2.4rem',
			'large-4': '1.8rem'
		},
		fontWeight: {
			hairline: '100',
			thin: '200',
			light: '300',
			normal: '400',
			medium: '500',
			semibold: '600',
			bold: '700',
			extrabold: '800',
			black: '900'
		},
		height: theme => ({
			auto: 'auto',
			...theme('spacing'),
			full: '100%',
			screen: '100vh'
		}),
		inset: {
			'0': '0',
			auto: 'auto'
		},
		letterSpacing: {
			'0.14neg': '-0.14px',
			'0.17neg': '-0.17px',
			'0.5': '0.5px',
			'0.75': '0.75px',
			'1': '0',
			'1.5': '1.5px',
			'1.75': '1.75px'
		},
		lineHeight: {
			none: '1',
		},
		listStyleType: {
			none: 'none',
			disc: 'disc',
			decimal: 'decimal',
			circle: 'circle',
			square: 'square',
			'lower-alpha': 'lower-alpha',
			'lower-roman': 'lower-roman'
		},
		margin: (theme, { negative }) => ({
			auto: 'auto',
			...theme('spacing'),
			...negative(theme('spacing'))
		}),
		maxHeight: {
			full: '100%',
			screen: '100vh'
		},
		maxWidth: {
			container: '1110px',
			'container-narrow': '760px',
			full: '100%',
			screen: '100vw',
			logo: '12.5rem'
		},
		minHeight: {
			'0': '0',
			full: '100%',
			screen: '100vh',
			auto: 'auto'
		},
		minWidth: {
			'0': '0',
			full: '100%',
			screen: '100vw'
		},
		objectPosition: {
			bottom: 'bottom',
			center: 'center',
			left: 'left',
			'left-bottom': 'left bottom',
			'left-top': 'left top',
			right: 'right',
			'right-bottom': 'right bottom',
			'right-top': 'right top',
			top: 'top'
		},
		opacity: {
			'0': '0',
			'25': '0.25',
			'50': '0.5',
			'75': '0.75',
			'90': '0.9',
			'100': '1'
		},
		order: {
			first: '-9999',
			last: '9999',
			none: '0',
			'1': '1',
			'2': '2',
			'3': '3',
			'4': '4',
			'5': '5',
			'6': '6',
			'7': '7',
			'8': '8',
			'9': '9',
			'10': '10',
			'11': '11',
			'12': '12'
		},
		padding: theme => theme('spacing'),
		stroke: {
			current: 'currentColor'
		},
		textColor: theme => theme('colors'),
		width: theme => ({
			auto: 'auto',
			...theme('spacing'),
			'1/2': '50%',
			'1/3': '33.333333%',
			'2/3': '66.666667%',
			'1/4': '25%',
			'2/4': '50%',
			'3/4': '75%',
			'1/5': '20%',
			'2/5': '40%',
			'3/5': '60%',
			'4/5': '80%',
			'1/6': '16.666667%',
			'2/6': '33.333333%',
			'3/6': '50%',
			'4/6': '66.666667%',
			'5/6': '83.333333%',
			'3/8': '35.5%',
			'5/8': '62.5%',
			'1/12': '8.333333%',
			'2/12': '16.666667%',
			'3/12': '25%',
			'4/12': '33.333333%',
			'5/12': '41.666667%',
			'6/12': '50%',
			'7/12': '58.333333%',
			'8/12': '66.666667%',
			'9/12': '75%',
			'10/12': '83.333333%',
			'11/12': '91.666667%',
			full: '100%',
			screen: '100vw'
		}),
		zIndex: {
			auto: 'auto',
			'0': '0',
			'10': '10',
			'20': '20',
			'30': '30',
			'40': '40',
			'50': '50',
			'-10': '-10',
			'-20': '-20',
			'-30': '-30',
			'-40': '-40',
			'-50': '-50'
		},
	},
	variants: {
		alignContent: ['responsive'],
		alignItems: ['responsive'],
		alignSelf: ['responsive'],
		appearance: ['responsive'],
		backgroundAttachment: ['responsive'],
		backgroundColor: ['responsive', 'hover', 'focus'],
		backgroundPosition: ['responsive'],
		backgroundRepeat: ['responsive'],
		backgroundSize: ['responsive'],
		borderCollapse: ['responsive'],
		borderColor: ['responsive', 'hover', 'focus'],
		borderRadius: ['responsive'],
		borderStyle: ['responsive'],
		borderWidth: ['responsive'],
		boxShadow: ['responsive', 'hover', 'focus'],
		cursor: ['responsive'],
		display: ['responsive'],
		fill: ['responsive'],
		flex: ['responsive'],
		flexDirection: ['responsive'],
		flexGrow: ['responsive'],
		flexShrink: ['responsive'],
		flexWrap: ['responsive'],
		float: ['responsive'],
		fontFamily: ['responsive'],
		fontSize: ['responsive'],
		fontSmoothing: ['responsive'],
		fontStyle: ['responsive'],
		fontWeight: ['responsive', 'hover', 'focus'],
		height: ['responsive'],
		inset: ['responsive'],
		justifyContent: ['responsive'],
		letterSpacing: ['responsive'],
		lineHeight: ['responsive'],
		listStylePosition: ['responsive'],
		listStyleType: ['responsive'],
		margin: ['responsive', 'first', 'last'],
		maxHeight: ['responsive'],
		maxWidth: ['responsive'],
		minHeight: ['responsive'],
		minWidth: ['responsive'],
		objectFit: ['responsive'],
		objectPosition: ['responsive'],
		opacity: ['responsive', 'hover'],
		order: ['responsive'],
		outline: ['responsive', 'focus'],
		overflow: ['responsive'],
		padding: ['responsive', 'first', 'last'],
		pointerEvents: ['responsive'],
		position: ['responsive'],
		resize: ['responsive'],
		stroke: ['responsive'],
		tableLayout: ['responsive'],
		textAlign: ['responsive'],
		textColor: ['responsive', 'hover', 'focus', 'group-hover'],
		textDecoration: ['responsive', 'hover', 'focus'],
		textTransform: ['responsive'],
		userSelect: ['responsive'],
		verticalAlign: ['responsive'],
		visibility: ['responsive'],
		whitespace: ['responsive'],
		width: ['responsive'],
		wordBreak: ['responsive'],
		zIndex: ['responsive']
	},
	corePlugins: {},
	plugins: [],
}
