# Linter Options
options:
  # Don't merge default rules
  merge-default-rules: false
    # Set the formatter to 'html'
  formatter: stylish
rules:
  extends-before-mixins: 2
  extends-before-declarations: 2
  placeholder-in-extend: 1
  mixins-before-declarations:
    - 2
    -
      exclude:
        - breakpoint
        - mq
        - placeholder
        - media
  no-warn: 1
  no-debug: 1
  no-ids: 1
  no-important: 3
  hex-notation:
    - 2
    -
      style: uppercase
  indentation:
    - 2
    -
      size: 2
  property-sort-order:
    - 1
    -
      order:
        - display
        - margin
      ignore-custom-properties: true
  variable-for-property:
    - 2
    -
      properties:
        - color
  quotes:
    - 2
    -
      style: single
  brace-style:
    - 2
    -
      style: 1tbs
      allow-single-line: false
  empty-line-between-blocks:
    - 2
    -
      include: true
  space-after-colon: 2
  space-after-bang: 2
  space-after-comma: 2
  space-around-operator: 2
  space-before-brace: 2
  space-before-colon: 2
  space-between-parens: 2
  trailing-semicolon: 2
  url-quotes: 2
  zero-unit: 2
